# Generated by Django 5.1.4 on 2025-01-28 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
